# Generated by Django 5.2.3 on 2025-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a valid phone number (e.g. +8801234567890)', max_length=15, verbose_name='Phone Number'),
        ),
    ]
