# Generated by Django 5.2.3 on 2025-08-28 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(related_name='rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
