# Generated by Django 5.2.3 on 2025-08-08 14:48

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_link',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default.png', null=True, upload_to=events.models.file_location),
        ),
    ]
