# Generated by Django 5.2.3 on 2025-08-08 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_link_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(related_name='rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
